// MaterialCommunityIcons glyph names.
// NOTE: 'warning' uses 'alert' (MCI has no 'alert-triangle' glyph).
export const Icons = {
  home:             'home',
  map:              'map-marker-radius',
  wallet:           'wallet',
  profile:          'account',
  menu:             'menu',
  back:             'arrow-right',
  next:             'arrow-left',
  close:            'close',
  locationPin:      'map-marker',
  locationUser:     'crosshairs-gps',
  carTop:           'car',
  navigation:       'navigation',
  search:           'magnify',
  mic:              'microphone',
  phone:            'phone',
  chat:             'message-text',
  share:            'share-variant',
  swap:             'swap-vertical',
  plus:             'plus',
  camera:           'camera',
  edit:             'pencil',
  card:             'credit-card',
  cash:             'cash',
  topup:            'arrow-up-circle',
  withdraw:         'arrow-down-circle',
  send:             'send',
  star:             'star',
  starEmpty:        'star-outline',
  check:            'check-circle',
  warning:          'alert',
  bell:             'bell',
  clock:            'clock-outline',
  fire:             'fire',
  shield:           'shield-check',
  sos:              'alert-octagon',
  verified:         'check-decagram',
  house:            'home-account',
  work:             'briefcase',
  logout:           'logout',
  help:             'help-circle',
  terms:            'file-document',
  settings:         'cog',
  flag:             'flag',
  luggage:          'bag-suitcase',
  calendar:         'calendar',
  percent:          'percent',
  license:          'card-account-details',
  trash:            'trash-can',
  moon:             'weather-night',
  distance:         'map-marker-distance',
  language:         'translate',
  chevronRight:     'chevron-left',
  gift:             'gift',
  refund:           'cash-refund',
  google:           'google',
  whatsapp:         'whatsapp',
  facebook:         'facebook',
  instagram:        'instagram',
} as const

export type IconName = keyof typeof Icons
